### PR TITLE
Check all results of zpl_alloc() when using JSON parser/writer

### PR DESCRIPTION
**Pull request by rheatley-pervasid**
Conversation in https://github.com/zpl-c/zpl/issues/104

### CODE REVIEW

**Comment by inlife** [comment]
Overall, it looks fantastic! One of the most essential additions here is the function call status handling which was not part of the library.

We discussed with @zpl-zak that, and so far, it is the most straightforward approach to status handling. 

@rheatley-pervasid, what do you think about changing zpl_b8 signature to a custom bool type zpl_result {true/false}? Would that improve the notion of type of return value for the end users of the library?

Thank you so much on all the efforts you've put it!

**Comment by rheatley-pervasid** [comment]
@inlife it is definitely worth more thought. As @zpl-zak pointed out on https://github.com/zpl-c/zpl/issues/104 there are still a lot more functions that would get this attention.
I would be tempted to suggest tackling them first, then if it is clear that zpl_result would cover most cases, it seems attractive. I would also hope, a relatively simple change - almost just a carefully constructed `sed`.
At this point, I am not confident what percentage of functions can use false/true for failure/success, compared to the opposite model of 1/0 for failure/success.

There are at least a few other functions using a bool return, e.g. ZPL_FILE_*_PROC so I am continuing that paradigm hopefully, rather than starting a new one.

**Comment by inlife** [comment]
Ok, I think you are right in the sense that it should be a different task on its own and can be done separately. 

Overall I think we are good to merge @zpl-zak 👍 

Thank you for the amazing addition @rheatley-pervasid! So far potentially might be one of the biggest additions ever made by a contributor! 🎉🎉

**Review by inlife — APPROVED** [review]

**Review by zpl-zak — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
