### PR TITLE
ZPL_PLATFORM_CYGWIN

### PR DESCRIPTION
**Pull request by funZX**
Compile for cygwin: `ZPL_PLATFORM_CYGWIN`.
Fixed a 0 sized array allocation.

### CODE REVIEW

**Comment by zaklaus** [comment]
Hi, was this intended to be closed?

**Comment by funZX** [comment]
Hi Dominik!Yes, for now... sorry I didn't comment. 
I have an issue now in my project, where although it compiles it doesn't link complaining about duplicate "zpl_free", "zpl_heap_allocator" and "zpl_char_last_occurence" symbols.
 I will reopen it once I fix this.  That zero length allocation bug is valid though. Maybe you can add it regardless of CYGWIN platform support?



    On Monday, February 3, 2020, 10:59:23 AM GMT+2, Dominik Madarász <notifications@github.com> wrote:  
 
 
Hi, was this intended to be closed?

**Comment by zaklaus** [comment]
Thank you for responding @funZX, I will apply your fix regarding zero-length allocation then. Also, @inlife has fixed an issue that could be somehow related to yours, you could check out the latest release to see if your issues persist. In any case thank you for your contribution!

**Comment by funZX** [comment]
Thank you! It works perfectly in Cygwin too.

**Comment by zaklaus** [comment]
Glad to hear that! We will review the changes and merge it afterwards, once again, thank you for your contribution!

**Pull request merged**
